-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 09:41:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`annees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`annees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`annees` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `annee` SMALLINT UNSIGNED NOT NULL,
  `statut` ENUM('ouvert', 'cloture') NOT NULL DEFAULT 'ouvert',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `annees_annee_unique` (`annee` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_slug_unique` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'Slug machine : ex valider-evaluation',
  `slug` VARCHAR(255) NOT NULL COMMENT 'Libellé lisible : ex Valider une évaluation',
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `permissions_name_unique` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`subjective_criteria_templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subjective_criteria_templates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subjective_criteria_templates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordre` INT UNSIGNED NOT NULL DEFAULT 0,
  `titre` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cache` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cache` (
  `key` VARCHAR(255) NOT NULL,
  `value` MEDIUMTEXT NOT NULL,
  `expiration` INT NOT NULL,
  PRIMARY KEY (`key`),
  INDEX `cache_expiration_index` (`expiration` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cache_locks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cache_locks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cache_locks` (
  `key` VARCHAR(255) NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `expiration` INT NOT NULL,
  PRIMARY KEY (`key`),
  INDEX `cache_locks_expiration_index` (`expiration` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jobs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT UNSIGNED NOT NULL,
  `reserved_at` INT UNSIGNED NULL DEFAULT NULL,
  `available_at` INT UNSIGNED NOT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_reserved_available_index` (`queue` ASC, `reserved_at` ASC, `available_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`job_batches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_batches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_batches` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `total_jobs` INT NOT NULL,
  `pending_jobs` INT NOT NULL,
  `failed_jobs` INT NOT NULL,
  `failed_job_ids` LONGTEXT NOT NULL,
  `options` MEDIUMTEXT NULL DEFAULT NULL,
  `cancelled_at` INT NULL DEFAULT NULL,
  `created_at` INT NOT NULL,
  `finished_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`password_reset_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`password_reset_tokens` ;

CREATE TABLE IF NOT EXISTS `mydb`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`login_failures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login_failures` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login_failures` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `attempted_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `login_failures_email_index` (`email` ASC) VISIBLE,
  INDEX `login_failures_ip_address_index` (`ip_address` ASC) VISIBLE,
  INDEX `login_failures_attempted_at_index` (`attempted_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`entites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entites` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NULL DEFAULT NULL,
  `secretariat_telephone` VARCHAR(30) NULL DEFAULT NULL,
  `dg_agent_id` BIGINT UNSIGNED NULL,
  `dga_agent_id` BIGINT UNSIGNED NULL,
  `pca_agent_id` BIGINT UNSIGNED NULL,
  `assistante_agent_id` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `entites_nom_unique` (`nom` ASC) VISIBLE,
  INDEX `entites_dg_agent_id_foreign` (`dg_agent_id` ASC) VISIBLE,
  INDEX `entites_dga_agent_id_foreign` (`dga_agent_id` ASC) VISIBLE,
  INDEX `entites_pca_agent_id_foreign` (`pca_agent_id` ASC) VISIBLE,
  INDEX `entites_assistante_agent_id_foreign` (`assistante_agent_id` ASC) VISIBLE,
  CONSTRAINT `entites_dg_agent_id_foreign`
    FOREIGN KEY (`dg_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `entites_dga_agent_id_foreign`
    FOREIGN KEY (`dga_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `entites_pca_agent_id_foreign`
    FOREIGN KEY (`pca_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `entites_assistante_agent_id_foreign`
    FOREIGN KEY (`assistante_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`directions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`directions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`directions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `entite_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `directeur_agent_id` BIGINT UNSIGNED NOT NULL,
  `secretaire_agent_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `directions_entite_id_foreign` (`entite_id` ASC) VISIBLE,
  INDEX `directions_directeur_agent_id_foreign` (`directeur_agent_id` ASC) VISIBLE,
  INDEX `directions_secretaire_agent_id_foreign` (`secretaire_agent_id` ASC) VISIBLE,
  CONSTRAINT `directions_entite_id_foreign`
    FOREIGN KEY (`entite_id`)
    REFERENCES `mydb`.`entites` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `directions_directeur_agent_id_foreign`
    FOREIGN KEY (`directeur_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `directions_secretaire_agent_id_foreign`
    FOREIGN KEY (`secretaire_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`delegation_techniques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`delegation_techniques` ;

CREATE TABLE IF NOT EXISTS `mydb`.`delegation_techniques` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `entite_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `region` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `secretariat_telephone` VARCHAR(30) NULL DEFAULT NULL,
  `directeur_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `secretaire_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `delegation_techniques_region_ville_unique` (`region` ASC, `ville` ASC) VISIBLE,
  INDEX `delegation_techniques_entite_id_foreign` (`entite_id` ASC) VISIBLE,
  INDEX `delegation_techniques_directeur_agent_id_foreign` (`directeur_agent_id` ASC) VISIBLE,
  INDEX `delegation_techniques_secretaire_agent_id_foreign` (`secretaire_agent_id` ASC) VISIBLE,
  CONSTRAINT `delegation_techniques_entite_id_foreign`
    FOREIGN KEY (`entite_id`)
    REFERENCES `mydb`.`entites` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `delegation_techniques_directeur_agent_id_foreign`
    FOREIGN KEY (`directeur_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `delegation_techniques_secretaire_agent_id_foreign`
    FOREIGN KEY (`secretaire_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`villes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`villes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`villes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `delegation_technique_id` BIGINT UNSIGNED NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `villes_dt_nom_unique` (`delegation_technique_id` ASC, `nom` ASC) VISIBLE,
  INDEX `villes_delegation_technique_id_foreign` (`delegation_technique_id` ASC) VISIBLE,
  CONSTRAINT `villes_delegation_technique_id_foreign`
    FOREIGN KEY (`delegation_technique_id`)
    REFERENCES `mydb`.`delegation_techniques` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`caisses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`caisses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`caisses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `delegation_technique_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ville_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `annee_ouverture` VARCHAR(4) NULL DEFAULT NULL,
  `quartier` VARCHAR(255) NULL DEFAULT NULL,
  `secretariat_telephone` VARCHAR(30) NULL DEFAULT NULL,
  `directeur_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `secretaire_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `caisses_nom_unique` (`nom` ASC) VISIBLE,
  INDEX `caisses_delegation_technique_id_foreign` (`delegation_technique_id` ASC) VISIBLE,
  INDEX `caisses_ville_id_foreign` (`ville_id` ASC) VISIBLE,
  INDEX `caisses_directeur_agent_id_foreign` (`directeur_agent_id` ASC) VISIBLE,
  INDEX `caisses_secretaire_agent_id_foreign` (`secretaire_agent_id` ASC) VISIBLE,
  CONSTRAINT `caisses_delegation_technique_id_foreign`
    FOREIGN KEY (`delegation_technique_id`)
    REFERENCES `mydb`.`delegation_techniques` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `caisses_ville_id_foreign`
    FOREIGN KEY (`ville_id`)
    REFERENCES `mydb`.`villes` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `caisses_directeur_agent_id_foreign`
    FOREIGN KEY (`directeur_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `caisses_secretaire_agent_id_foreign`
    FOREIGN KEY (`secretaire_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`agences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agences` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agences` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `delegation_technique_id` BIGINT UNSIGNED NOT NULL,
  `caisse_id` BIGINT UNSIGNED NOT NULL COMMENT 'Caisse parente',
  `chef_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `secretaire_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `agences_delegation_nom_unique` (`delegation_technique_id` ASC, `nom` ASC) VISIBLE,
  INDEX `agences_delegation_technique_id_foreign` (`delegation_technique_id` ASC) VISIBLE,
  INDEX `agences_caisse_id_foreign` (`caisse_id` ASC) VISIBLE,
  INDEX `agences_chef_agent_id_foreign` (`chef_agent_id` ASC) VISIBLE,
  INDEX `agences_secretaire_agent_id_foreign` (`secretaire_agent_id` ASC) VISIBLE,
  CONSTRAINT `agences_delegation_technique_id_foreign`
    FOREIGN KEY (`delegation_technique_id`)
    REFERENCES `mydb`.`delegation_techniques` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `agences_caisse_id_foreign`
    FOREIGN KEY (`caisse_id`)
    REFERENCES `mydb`.`caisses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `agences_chef_agent_id_foreign`
    FOREIGN KEY (`chef_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agences_secretaire_agent_id_foreign`
    FOREIGN KEY (`secretaire_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`guichets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`guichets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`guichets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `agence_id` BIGINT UNSIGNED NOT NULL,
  `chef_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `guichets_agence_id_foreign` (`agence_id` ASC) VISIBLE,
  INDEX `guichets_chef_agent_id_foreign` (`chef_agent_id` ASC) VISIBLE,
  CONSTRAINT `guichets_agence_id_foreign`
    FOREIGN KEY (`agence_id`)
    REFERENCES `mydb`.`agences` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `guichets_chef_agent_id_foreign`
    FOREIGN KEY (`chef_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`services` ;

CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `direction_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Service d une Direction centrale (exclusif)',
  `delegation_technique_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Service d une DT (exclusif)',
  `caisse_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Service d une Caisse (exclusif)',
  `chef_agent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `services_direction_id_foreign` (`direction_id` ASC) VISIBLE,
  INDEX `services_delegation_technique_id_foreign` (`delegation_technique_id` ASC) VISIBLE,
  INDEX `services_caisse_id_foreign` (`caisse_id` ASC) VISIBLE,
  INDEX `services_chef_agent_id_foreign` (`chef_agent_id` ASC) VISIBLE,
  CONSTRAINT `services_direction_id_foreign`
    FOREIGN KEY (`direction_id`)
    REFERENCES `mydb`.`directions` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `services_delegation_technique_id_foreign`
    FOREIGN KEY (`delegation_technique_id`)
    REFERENCES `mydb`.`delegation_techniques` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `services_caisse_id_foreign`
    FOREIGN KEY (`caisse_id`)
    REFERENCES `mydb`.`caisses` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `services_chef_agent_id_foreign`
    FOREIGN KEY (`chef_agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`agents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agents` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `entite_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Direction Générale — DG, DGA, PCA, Assistante_Dg, Conseillers_Dg, Secrétariat DG',
  `direction_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Direction fonctionnelle — agents des services centraux (DRH, DAF, DTIC…)',
  `delegation_technique_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'DT de rattachement',
  `caisse_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Caisse de rattachement',
  `agence_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Agence de rattachement',
  `guichet_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Guichet de rattachement',
  `service_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Service de rattachement',
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `sexe` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(191) NOT NULL COMMENT 'Email professionnel',
  `numero_telephone` VARCHAR(30) NULL DEFAULT NULL,
  `photo_path` VARCHAR(255) NULL DEFAULT NULL,
  `fonction` VARCHAR(100) NOT NULL,
  `date_debut_fonction` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `agents_email_unique` (`email` ASC) VISIBLE,
  INDEX `agents_entite_id_foreign` (`entite_id` ASC) VISIBLE,
  INDEX `agents_direction_id_foreign` (`direction_id` ASC) VISIBLE,
  INDEX `agents_delegation_technique_id_foreign` (`delegation_technique_id` ASC) VISIBLE,
  INDEX `agents_caisse_id_foreign` (`caisse_id` ASC) VISIBLE,
  INDEX `agents_agence_id_foreign` (`agence_id` ASC) VISIBLE,
  INDEX `agents_guichet_id_foreign` (`guichet_id` ASC) VISIBLE,
  INDEX `agents_service_id_foreign` (`service_id` ASC) VISIBLE,
  CONSTRAINT `agents_entite_id_foreign`
    FOREIGN KEY (`entite_id`)
    REFERENCES `mydb`.`entites` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agents_direction_id_foreign`
    FOREIGN KEY (`direction_id`)
    REFERENCES `mydb`.`directions` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agents_delegation_technique_id_foreign`
    FOREIGN KEY (`delegation_technique_id`)
    REFERENCES `mydb`.`delegation_techniques` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agents_caisse_id_foreign`
    FOREIGN KEY (`caisse_id`)
    REFERENCES `mydb`.`caisses` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agents_agence_id_foreign`
    FOREIGN KEY (`agence_id`)
    REFERENCES `mydb`.`agences` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agents_guichet_id_foreign`
    FOREIGN KEY (`guichet_id`)
    REFERENCES `mydb`.`guichets` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `agents_service_id_foreign`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `agent_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Lien vers la fiche Agent (FK ajoutée après création de agents)',
  `name` VARCHAR(191) NOT NULL COMMENT 'Nom complet affiché',
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `must_change_password` TINYINT(1) NOT NULL DEFAULT 1,
  `role` VARCHAR(50) NOT NULL DEFAULT 'Agent',
  `theme_preference` VARCHAR(50) NOT NULL DEFAULT 'reference',
  `manager_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Supérieur direct N+1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE,
  UNIQUE INDEX `users_agent_id_unique` (`agent_id` ASC) VISIBLE,
  INDEX `users_manager_id_foreign` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `users_manager_id_foreign`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `users_agent_id_foreign`
    FOREIGN KEY (`agent_id`)
    REFERENCES `mydb`.`agents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sessions` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `payload` LONGTEXT NOT NULL,
  `last_activity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sessions_user_id_index` (`user_id` ASC) VISIBLE,
  INDEX `sessions_last_activity_index` (`last_activity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`activites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activites` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `action` VARCHAR(255) NOT NULL COMMENT 'ex: CHANGEMENT_ROLE, VALIDATION_EVALUATION',
  `description` TEXT NOT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `activites_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `activites_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`permission_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permission_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permission_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `permission_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `permission_user_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `permission_user_permission_id_foreign` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `permission_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_user_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_user_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `role_user_role_id_foreign` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_user_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`roles_has_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles_has_permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles_has_permissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `permission_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_permissions_unique` (`role_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `roles_has_permissions_role_id_foreign` (`role_id` ASC) VISIBLE,
  INDEX `roles_has_permissions_permission_id_foreign` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `roles_has_permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `roles_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`objectifs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`objectifs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`objectifs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `assignable_type` VARCHAR(255) NOT NULL COMMENT 'Type polymorphique (ex: App\\\\Models\\\\Direction)',
  `assignable_id` BIGINT UNSIGNED NOT NULL,
  `annee_id` BIGINT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `date_echeance` DATE NOT NULL,
  `titre` VARCHAR(255) NOT NULL,
  `commentaire` TEXT NULL DEFAULT NULL,
  `avancement_percentage` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `objectifs_assignable_index` (`assignable_type` ASC, `assignable_id` ASC) VISIBLE,
  INDEX `objectifs_annee_id_foreign` (`annee_id` ASC) VISIBLE,
  CONSTRAINT `objectifs_annee_id_foreign`
    FOREIGN KEY (`annee_id`)
    REFERENCES `mydb`.`annees` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`fiche_objectifs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fiche_objectifs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fiche_objectifs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `annee_id` BIGINT UNSIGNED NOT NULL,
  `assignable_id` BIGINT UNSIGNED NOT NULL COMMENT 'Cible polymorphique (User, Direction…)',
  `assignable_type` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `date_echeance` DATE NOT NULL,
  `avancement_percentage` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `statut` ENUM('brouillon', 'en_attente', 'acceptee', 'refusee') NOT NULL DEFAULT 'brouillon',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fiche_objectifs_annee_id_foreign` (`annee_id` ASC) VISIBLE,
  INDEX `fiche_objectifs_assignable_index` (`assignable_type` ASC, `assignable_id` ASC) VISIBLE,
  CONSTRAINT `fiche_objectifs_annee_id_foreign`
    FOREIGN KEY (`annee_id`)
    REFERENCES `mydb`.`annees` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`fiche_objectif_objectifs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fiche_objectif_objectifs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fiche_objectif_objectifs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fiche_objectif_id` BIGINT UNSIGNED NOT NULL,
  `objectif_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `libelle` VARCHAR(255) NOT NULL,
  `indicateur_performance` TEXT NULL DEFAULT NULL,
  `poids` INT UNSIGNED NOT NULL DEFAULT 0,
  `note_obtenue` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fiche_objectif_objectifs_fiche_id_foreign` (`fiche_objectif_id` ASC) VISIBLE,
  INDEX `fiche_objectif_objectifs_objectif_id_foreign` (`objectif_id` ASC) VISIBLE,
  CONSTRAINT `fiche_objectif_objectifs_fiche_id_foreign`
    FOREIGN KEY (`fiche_objectif_id`)
    REFERENCES `mydb`.`fiche_objectifs` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fiche_objectif_objectifs_objectif_id_foreign`
    FOREIGN KEY (`objectif_id`)
    REFERENCES `mydb`.`objectifs` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evaluations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evaluations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evaluateur_id` BIGINT UNSIGNED NOT NULL,
  `evaluable_type` VARCHAR(255) NOT NULL COMMENT 'Type polymorphique (ex: App\\\\Models\\\\User)',
  `evaluable_id` BIGINT UNSIGNED NOT NULL,
  `evaluable_role` VARCHAR(255) NOT NULL DEFAULT 'agent',
  `fiche_objectif_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `annee_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `moyenne_subjectifs` DECIMAL(8,2) NULL DEFAULT NULL,
  `moyenne_objectifs` DECIMAL(8,2) NULL DEFAULT NULL,
  `note_criteres_subjectifs` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `note_criteres_objectifs` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `note_objectifs` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `note_manuelle` TINYINT UNSIGNED NULL DEFAULT NULL,
  `note_finale` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `commentaire` TEXT NULL DEFAULT NULL,
  `points_a_ameliorer` TEXT NULL DEFAULT NULL,
  `strategies_amelioration` TEXT NULL DEFAULT NULL,
  `commentaires_evalue` TEXT NULL DEFAULT NULL,
  `statut` ENUM('brouillon', 'soumis', 'valide', 'refuse') NOT NULL DEFAULT 'brouillon',
  `signature_evalue_nom` VARCHAR(255) NULL DEFAULT NULL,
  `date_signature_evalue` DATE NULL DEFAULT NULL,
  `signature_evaluateur_nom` VARCHAR(255) NULL DEFAULT NULL,
  `date_signature_evaluateur` DATE NULL DEFAULT NULL,
  `signature_directeur_nom` VARCHAR(255) NULL DEFAULT NULL,
  `date_signature_directeur` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `evaluations_evaluateur_id_foreign` (`evaluateur_id` ASC) VISIBLE,
  INDEX `evaluations_evaluable_index` (`evaluable_type` ASC, `evaluable_id` ASC) VISIBLE,
  INDEX `evaluations_fiche_objectif_id_foreign` (`fiche_objectif_id` ASC) VISIBLE,
  INDEX `evaluations_annee_id_foreign` (`annee_id` ASC) VISIBLE,
  CONSTRAINT `evaluations_evaluateur_id_foreign`
    FOREIGN KEY (`evaluateur_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `evaluations_fiche_objectif_id_foreign`
    FOREIGN KEY (`fiche_objectif_id`)
    REFERENCES `mydb`.`fiche_objectifs` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `evaluations_annee_id_foreign`
    FOREIGN KEY (`annee_id`)
    REFERENCES `mydb`.`annees` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`evaluation_identifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evaluation_identifications` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evaluation_identifications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evaluation_id` BIGINT UNSIGNED NOT NULL,
  `nom_prenom` VARCHAR(255) NULL DEFAULT NULL,
  `semestre` VARCHAR(20) NULL DEFAULT NULL,
  `date_evaluation` DATE NULL DEFAULT NULL,
  `matricule` VARCHAR(255) NULL DEFAULT NULL,
  `poste` VARCHAR(255) NULL DEFAULT NULL,
  `emploi` VARCHAR(255) NULL DEFAULT NULL,
  `niveau` VARCHAR(255) NULL DEFAULT NULL,
  `direction` VARCHAR(255) NULL DEFAULT NULL,
  `direction_service` VARCHAR(255) NULL DEFAULT NULL,
  `date_confirmation` DATE NULL DEFAULT NULL,
  `categorie` VARCHAR(255) NULL DEFAULT NULL,
  `anciennete` VARCHAR(255) NULL DEFAULT NULL,
  `sexe` VARCHAR(1) NULL DEFAULT NULL,
  `date_recrutement` DATE NULL DEFAULT NULL,
  `date_titularisation` DATE NULL DEFAULT NULL,
  `date_affectation` DATE NULL DEFAULT NULL,
  `date_naissance` DATE NULL DEFAULT NULL,
  `formations` JSON NULL DEFAULT NULL,
  `experiences` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `evaluation_identifications_evaluation_id_unique` (`evaluation_id` ASC) VISIBLE,
  CONSTRAINT `evaluation_identifications_evaluation_id_foreign`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `mydb`.`evaluations` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`subjective_subcriteria_templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subjective_subcriteria_templates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subjective_subcriteria_templates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subjective_criteria_template_id` BIGINT UNSIGNED NOT NULL,
  `ordre` INT UNSIGNED NOT NULL DEFAULT 0,
  `libelle` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcriterion_template_fk` (`subjective_criteria_template_id` ASC) VISIBLE,
  CONSTRAINT `subcriterion_template_fk`
    FOREIGN KEY (`subjective_criteria_template_id`)
    REFERENCES `mydb`.`subjective_criteria_templates` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`evaluation_criteres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evaluation_criteres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evaluation_criteres` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evaluation_id` BIGINT UNSIGNED NOT NULL,
  `type` VARCHAR(20) NOT NULL COMMENT 'objectif ou subjectif',
  `ordre` INT UNSIGNED NOT NULL DEFAULT 0,
  `titre` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `note_globale` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `observation` TEXT NULL DEFAULT NULL,
  `source_fiche_objectif_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `source_fiche_objectif_objectif_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `source_template_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `evaluation_criteres_evaluation_id_foreign` (`evaluation_id` ASC) VISIBLE,
  INDEX `evaluation_criteres_source_fiche_objectif_id_foreign` (`source_fiche_objectif_id` ASC) VISIBLE,
  INDEX `evaluation_criteres_source_fiche_objectif_objectif_id_foreign` (`source_fiche_objectif_objectif_id` ASC) VISIBLE,
  INDEX `evaluation_criteres_source_template_id_foreign` (`source_template_id` ASC) VISIBLE,
  CONSTRAINT `evaluation_criteres_evaluation_id_foreign`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `mydb`.`evaluations` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `evaluation_criteres_source_fiche_objectif_id_foreign`
    FOREIGN KEY (`source_fiche_objectif_id`)
    REFERENCES `mydb`.`fiche_objectifs` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `evaluation_criteres_source_fiche_objectif_objectif_id_foreign`
    FOREIGN KEY (`source_fiche_objectif_objectif_id`)
    REFERENCES `mydb`.`fiche_objectif_objectifs` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `evaluation_criteres_source_template_id_foreign`
    FOREIGN KEY (`source_template_id`)
    REFERENCES `mydb`.`subjective_criteria_templates` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`evaluation_sous_criteres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evaluation_sous_criteres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evaluation_sous_criteres` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evaluation_critere_id` BIGINT UNSIGNED NOT NULL,
  `ordre` INT UNSIGNED NOT NULL DEFAULT 0,
  `libelle` VARCHAR(255) NOT NULL,
  `note` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `observation` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `evaluation_sous_criteres_evaluation_critere_id_foreign` (`evaluation_critere_id` ASC) VISIBLE,
  CONSTRAINT `evaluation_sous_criteres_evaluation_critere_id_foreign`
    FOREIGN KEY (`evaluation_critere_id`)
    REFERENCES `mydb`.`evaluation_criteres` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`alertes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alertes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alertes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL DEFAULT 'personnalisee' COMMENT 'securite | personnalisee',
  `priorite` VARCHAR(255) NOT NULL DEFAULT 'moyenne' COMMENT 'basse | moyenne | haute | critique',
  `titre` VARCHAR(255) NOT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `statut` VARCHAR(255) NOT NULL DEFAULT 'active' COMMENT 'active | resolue | ignoree',
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `alertes_created_by_foreign` (`created_by` ASC) VISIBLE,
  CONSTRAINT `alertes_created_by_foreign`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`alerte_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alerte_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alerte_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alerte_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `lu` TINYINT(1) NOT NULL DEFAULT 0,
  `lu_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `alerte_user_alerte_id_user_id_unique` (`alerte_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `alerte_user_alerte_id_foreign` (`alerte_id` ASC) VISIBLE,
  INDEX `alerte_user_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `alerte_user_alerte_id_foreign`
    FOREIGN KEY (`alerte_id`)
    REFERENCES `mydb`.`alertes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `alerte_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`migrations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
